Project Overview

This Project aims to develop learning model for predicting the next word in a given sequence of words.
The model is built using Long short-term Memory(LSTM) networks. Which are well-suited for sequence prediction tasks. The project includes the following steps

1- Data Collection: We use the text of Shakesspere's "Hamlet" as our dataset. This rich, complex text provides a good challenge for our model.

2- Data Processing : the Text data is tokenized, converted into sequences, and padded to ensure uniform input lengths. the sequence are then split into trainig and testing sets.

3- Model Building : An LSTM model is constructed with an embedding layer. two LSTM layers abd dense output layer with a softmax activation function to predict the probability of next word.

4- Model Training: the model is trained using the prepared sequences, with early stopping implemented to prevent overfitting. Early stopping monitors the validation loss and stops training when the loss stops improving.

5- Model Evaluation: The Model is avaluated using a set of example sentences to test its ability to predict the bnext word accurately.

6- Deployment: A Stremalit web application is developed to allow users input a sequence of words and get the predicted next word in real-time.

In [2]:
## Data Collection

import nltk
nltk.download('gutenberg')
from nltk.corpus import gutenberg
import pandas as pd



## load the data set

data=gutenberg.raw('shakespeare-hamlet.txt')

## save to the file

with open('hamlet.txt','w') as f:
    f.write(data)



[nltk_data] Downloading package gutenberg to
[nltk_data]     C:\Users\vkumara\AppData\Roaming\nltk_data...
[nltk_data]   Package gutenberg is already up-to-date!


In [3]:
## data preprocessing

import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.model_selection import train_test_split




## load the dataset

with open('hamlet.txt','r') as f:
    text=f.read().lower()

## tokenization the text

tokenizer=Tokenizer()
tokenizer.fit_on_texts([text])
total_words=len(tokenizer.word_index)+1
total_words


c:\Users\vkumara\AppData\Local\anaconda3\Lib\site-packages\keras\src\export\tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):


4818

In [6]:
## create input sequences

input_sequences=[]
for line in text.split('\n'):
    token_list=tokenizer.texts_to_sequences([line])[0]
    for i in range(1,len(token_list)):
        n_gram_sequence=token_list[:i+1]
        input_sequences.append(n_gram_sequence)

In [7]:
input_sequences

[[1, 687],
 [1, 687, 4],
 [1, 687, 4, 45],
 [1, 687, 4, 45, 41],
 [1, 687, 4, 45, 41, 1886],
 [1, 687, 4, 45, 41, 1886, 1887],
 [1, 687, 4, 45, 41, 1886, 1887, 1888],
 [1180, 1889],
 [1180, 1889, 1890],
 [1180, 1889, 1890, 1891],
 [57, 407],
 [57, 407, 2],
 [57, 407, 2, 1181],
 [57, 407, 2, 1181, 177],
 [57, 407, 2, 1181, 177, 1892],
 [407, 1182],
 [407, 1182, 63],
 [408, 162],
 [408, 162, 377],
 [408, 162, 377, 21],
 [408, 162, 377, 21, 247],
 [408, 162, 377, 21, 247, 882],
 [18, 66],
 [451, 224],
 [451, 224, 248],
 [451, 224, 248, 1],
 [451, 224, 248, 1, 30],
 [408, 407],
 [451, 25],
 [408, 6],
 [408, 6, 43],
 [408, 6, 43, 62],
 [408, 6, 43, 62, 1893],
 [408, 6, 43, 62, 1893, 96],
 [408, 6, 43, 62, 1893, 96, 18],
 [408, 6, 43, 62, 1893, 96, 18, 566],
 [451, 71],
 [451, 71, 51],
 [451, 71, 51, 1894],
 [451, 71, 51, 1894, 567],
 [451, 71, 51, 1894, 567, 378],
 [451, 71, 51, 1894, 567, 378, 80],
 [451, 71, 51, 1894, 567, 378, 80, 3],
 [451, 71, 51, 1894, 567, 378, 80, 3, 273],
 [451, 71

In [8]:
## apply Pad sequence

max_sequence_len=max([len(x) for x in input_sequences])
max_sequence_len

14

In [9]:
input_sequences=np.array(pad_sequences(input_sequences,maxlen=max_sequence_len,padding='pre'))
input_sequences


array([[   0,    0,    0, ...,    0,    1,  687],
       [   0,    0,    0, ...,    1,  687,    4],
       [   0,    0,    0, ...,  687,    4,   45],
       ...,
       [   0,    0,    0, ...,    4,   45, 1047],
       [   0,    0,    0, ...,   45, 1047,    4],
       [   0,    0,    0, ..., 1047,    4,  193]])

In [10]:
## Create Predictors and labels

import tensorflow as tf

x,y=input_sequences[:,:-1],input_sequences[:,-1]
y=tf.keras.utils.to_categorical(y,num_classes=total_words)
x,y

(array([[   0,    0,    0, ...,    0,    0,    1],
        [   0,    0,    0, ...,    0,    1,  687],
        [   0,    0,    0, ...,    1,  687,    4],
        ...,
        [   0,    0,    0, ...,  687,    4,   45],
        [   0,    0,    0, ...,    4,   45, 1047],
        [   0,    0,    0, ...,   45, 1047,    4]]),
 array([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]))

In [11]:
#split the data into training and testing

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [15]:
## Train our LSTM RNN
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,Dense,LSTM,Dropout


## define the model
model=Sequential()
model.add(Embedding(total_words,100,input_length=max_sequence_len-1))
model.add(LSTM(150, return_sequences=True))
model.add(Dropout(0.2))
model.add(LSTM(100))
model.add(Dense(total_words,activation='softmax'))


## compile the model
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
model.summary()

c:\Users\vkumara\AppData\Local\anaconda3\Lib\site-packages\keras\src\layers\core\embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_4 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_2 (Dropout)             │ ?                      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_5 (LSTM)                   │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [16]:
## train the model
history=model.fit(x_train,y_train,epochs=50,validation_data=(x_test,y_test), verbose=1)

Epoch 1/50
644/644 ━━━━━━━━━━━━━━━━━━━━ 50s 62ms/step - accuracy: 0.0327 - loss: 6.9062 - val_accuracy: 0.0356 - val_loss: 6.7476
Epoch 2/50
644/644 ━━━━━━━━━━━━━━━━━━━━ 41s 64ms/step - accuracy: 0.0377 - loss: 6.4647 - val_accuracy: 0.0431 - val_loss: 6.8259
Epoch 3/50
644/644 ━━━━━━━━━━━━━━━━━━━━ 40s 62ms/step - accuracy: 0.0454 - loss: 6.3200 - val_accuracy: 0.0493 - val_loss: 6.8638
Epoch 4/50
644/644 ━━━━━━━━━━━━━━━━━━━━ 37s 58ms/step - accuracy: 0.0510 - loss: 6.1766 - val_accuracy: 0.0501 - val_loss: 6.8952
Epoch 5/50
644/644 ━━━━━━━━━━━━━━━━━━━━ 40s 62ms/step - accuracy: 0.0545 - loss: 6.0409 - val_accuracy: 0.0569 - val_loss: 6.9104
Epoch 6/50
644/644 ━━━━━━━━━━━━━━━━━━━━ 36s 55ms/step - accuracy: 0.0608 - loss: 5.8964 - val_accuracy: 0.0618 - val_loss: 7.0051
Epoch 7/50
644/644 ━━━━━━━━━━━━━━━━━━━━ 37s 58ms/step - accuracy: 0.0662 - loss: 5.7599 - val_accuracy: 0.0653 - val_loss: 7.0804
Epoch 8/50
644/644 ━━━━━━━━━━━━━━━━━━━━ 37s 58ms/step - accuracy: 0.0739 - loss: 5.6279 - 

In [17]:
## Function to predict the next word
def predict_next_word(model, tokenizer, text, max_sequence_len):
    token_list = tokenizer.texts_to_sequences([text])[0]
    if len(token_list) >= max_sequence_len:
        token_list = token_list[-(max_sequence_len - 1):] ## ENsure the input length matches max_sequence_len
    token_list = pad_sequences([token_list], maxlen=max_sequence_len - 1, padding='pre')
    predicted = model.predict(token_list, verbose=0)
    predicted_word_index = np.argmax(predicted, axis=1)[0]
    for word, index in tokenizer.word_index.items():
        if index == predicted_word_index:
            return word 
        return None


In [22]:
input_text = "Enter Barnardo and Francisco"
print(f"Input Text: {input_text}")
max_sequence_len= model.input_shape[1] + 1
next_word = predict_next_word(model, tokenizer, input_text, max_sequence_len)
print(f"Next Word prediction : {next_word}")

Input Text: Enter Barnardo and Francisco
Next Word prediction : None


In [19]:
## save the model

model.save('next_word_lstm.h5')


# # save the tokenizer
import pickle
with open('tokenizer.pickle','wb') as handle:
    pickle.dump(tokenizer,handle,protocol=pickle.HIGHEST_PROTOCOL)